import dynamic from "next/dynamic";
import Head from "next/head";

const App = dynamic(async () => import('@/app'), {
  ssr: false
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Anatomy Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <App />
    </>
  );
}
